'use client';
import { useEffect, useMemo, useState } from 'react';
import JSZip from 'jszip';
import DashboardOperationsWorkspace from './DashboardOperationsWorkspace';
import FilingTrackerWorkspace from './FilingTrackerWorkspace';
import GuidedSourceDataFlow from './GuidedSourceDataFlow';
import OutputReviewWorkspace, { type ReviewOutput } from './OutputReviewWorkspace';
import type { FinalPdfPacket } from './PdfPacketPreview';
import TemplateProgressiveWorkspace from './TemplateProgressiveWorkspace';
import WorkspaceSettingsPanel from './WorkspaceSettingsPanel';
import { addFinalFilings, clearOperationsRecords, exportOperationsRecords, loadClientCases, loadFilings, markFilingSent, upsertClientCase, type ClientCaseRecord, type ClientCaseStatus, type FilingRecord } from '../lib/client-operations-store';
import { assembleFinalPdf, type PdfPacketPart } from '../lib/final-pdf-packet';
import { addOrderedPacketFolders } from '../lib/ordered-packet-archive';
import { isDocx, renderReferenceDisputeDocx } from '../lib/docx-renderer';
import { highlightTextInDocx } from '../lib/docx-review-marker';
import { renderLatePaymentReference } from '../lib/late-reference-renderer';
import { resolveAffidavitJurisdiction } from '../lib/affidavit-jurisdiction';
import { bureauInfo, bureaus, createNormalizedSourceCopy, detectRoutes, ftcFraudMonthYearFromReportDate, MAX_FTC_ACCOUNTS, parseSource, validFtcAccounts, type Bureau, type FtcAffectedAccount, type LetterRoute, type LetterType } from '../lib/letter-engine';
import { loadPacketAssets, type PacketAssets } from '../lib/packet-assets';
import { createSupportingDocumentsPdf } from '../lib/packet-renderer';
import { defaultReferences, loadReferenceMeta, readReferenceFile, removeReferenceFile, saveReferenceFile, saveReferenceMeta, type LetterReference, type Round } from '../lib/reference-store';
import { renderMappedAppendix } from '../lib/supplemental-template-renderer';
import { unresolvedCustomTemplateFields } from '../lib/template-contracts';
import { exhibitTitles, loadTemplateExhibits, readTemplateExhibit, type ExhibitKind, type TemplateExhibits } from '../lib/template-exhibits';
import { defaultWorkspacePreferences, loadWorkspacePreferences, saveWorkspacePreferences, type WorkspacePreferences } from '../lib/workspace-preferences';
type Panel = 'Dashboard' | 'Templates' | 'Source Data' | 'Outputs' | 'Filing Tracker' | 'Settings';
type SourceDraftSnapshot = { text: string; normalized: boolean; label: string; capturedAt: string };
const panels: Panel[] = ['Dashboard', 'Templates', 'Source Data', 'Outputs', 'Filing Tracker', 'Settings'];
const labels: Record<LetterType, string> = { DISPUTE: 'Dispute Letter', LATE_PAYMENT: 'Late Payment Letter' };
const requirements: ExhibitKind[] = ['FCRA', 'AFFIDAVIT', 'ATTACHMENT', 'FTC'];
const emptyEvidence = (): PacketAssets => ({ supporting: [], legalPdf: null });
const emptyTemplates = (): TemplateExhibits => ({ FCRA: null, AFFIDAVIT: null, ATTACHMENT: null, FTC: null });
const dateNow = () => new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'America/New_York' }).format(new Date());
const clean = (v: string) => (v || 'CLIENT').replace(/[\/:*?"<>|]+/g, '').replace(/\s+/g, ' ').trim().toUpperCase();
const base = (v: string) => clean(v).replace(/[^A-Z0-9]+/g, '_');
const order = (t: LetterType) => t === 'LATE_PAYMENT' ? ['01 Late Payment Letter', '02 Supporting Documents'] : ['01 Dispute Letter', '02 Supporting Documents', '03 FCRA', '04 Affidavit', '05 Attachment', '06 FTC'];
function download(name: string, blob: Blob) { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function normalizedFtcAccounts(items: FtcAffectedAccount[], reportDate: string) { const began = ftcFraudMonthYearFromReportDate(reportDate); return items.slice(0, MAX_FTC_ACCOUNTS).map((item) => ({ ...item, fraudBegan: began })); }
function ftcSection(items: FtcAffectedAccount[], reportDate: string) { return ['FTC AFFECTED ACCOUNTS', ...normalizedFtcAccounts(items, reportDate).flatMap((x, i) => [i ? '' : '', `Account Name: ${x.accountName}`, `Account Number: ${x.accountNumber}`, `Fraud Began: ${x.fraudBegan}`, `Date Discovered: ${x.dateDiscovered}`, `Fraudulent Amount: ${x.fraudulentAmount}`])].join('\n'); }
export default function LetterGeneratorWorkspaceV2() {
 const [panel, setPanel] = useState<Panel>('Dashboard'), [round, setRound] = useState<Round>('1st Round'), [preferences, setPreferences] = useState<WorkspacePreferences>(defaultWorkspacePreferences);
 const [references, setReferences] = useState<LetterReference[]>(defaultReferences), [source, setSource] = useState(''), [originalSource, setOriginalSource] = useState(''), [recoveryDraft, setRecoveryDraft] = useState<SourceDraftSnapshot | null>(null), [normalized, setNormalized] = useState(false), [caseId, setCaseId] = useState('');
 const [cases, setCases] = useState<ClientCaseRecord[]>([]), [filings, setFilings] = useState<FilingRecord[]>([]), [evidence, setEvidence] = useState<PacketAssets>(emptyEvidence), [templates, setTemplates] = useState<TemplateExhibits>(emptyTemplates);
 const [docs, setDocs] = useState<ReviewOutput[]>([]), [warnings, setWarnings] = useState<string[]>([]), [workingZip, setWorkingZip] = useState<{ name: string; blob: Blob } | null>(null), [packets, setPackets] = useState<FinalPdfPacket[]>([]), [finalZip, setFinalZip] = useState<{ name: string; blob: Blob } | null>(null), [docDate, setDocDate] = useState(''), [busy, setBusy] = useState(false), [finalizing, setFinalizing] = useState(false);
 const [, setStatus] = useState('Configure packet templates, then load a client source file.');
 useEffect(() => { const p = loadWorkspacePreferences(); setPreferences(p); setRound(p.defaultRound); setReferences(loadReferenceMeta()); setCases(loadClientCases()); setFilings(loadFilings()); }, []);
 useEffect(() => saveReferenceMeta(references), [references]); useEffect(() => setTemplates(loadTemplateExhibits(round)), [round]);
 const refs = references.filter((x) => x.round === round), parsed = useMemo(() => parseSource(source), [source]), routes = useMemo(() => detectRoutes(parsed), [parsed]);
 const verified = normalized && Boolean(parsed.name), evidenceKey = caseId ? `${round}::${caseId}` : '';
 const missingLetters = Array.from(new Set(routes.map((r) => r.type))).filter((type) => !refs.find((x) => x.type === type)?.file), dispute = routes.some((r) => r.type === 'DISPUTE'), disputed = bureaus.some((b) => parsed.dispute[b].length > 0);
 const affidavitRequired = Boolean(templates.AFFIDAVIT && disputed), affidavitJurisdiction = useMemo(() => resolveAffidavitJurisdiction(parsed), [parsed]);
 const affidavitSource = useMemo(() => ({ ...parsed, address: parsed.address.length ? parsed.address : ['N/A'], affidavitState: affidavitJurisdiction.state, affidavitCounty: affidavitJurisdiction.county }), [parsed, affidavitJurisdiction]);
 const sourceWarnings = [...parsed.diagnostics.filter((x) => x.level === 'warning'), ...(affidavitRequired && affidavitJurisdiction.reviewRequired ? [{ message: affidavitJurisdiction.explanation }] : [])];
 const affidavitReady = !affidavitRequired || Boolean(affidavitSource.affidavitState.trim() && affidavitSource.affidavitCounty.trim());
 const ftcRequired = Boolean(templates.FTC && dispute), ftcReady = !ftcRequired || Boolean(parsed.ftcReportNumber.trim() && parsed.ftcReportDate.trim() && parsed.firstName.trim() && parsed.lastName.trim() && validFtcAccounts(parsed.ftcAccounts));
 const customFields = unresolvedCustomTemplateFields([...refs.map((x) => x.contract), ...Object.values(templates).map((x) => x?.contract)]), customReady = customFields.every((x) => !x.required || Boolean(parsed.templateFields[x.key]?.trim()));
 const missingNodes = dispute ? requirements.filter((k) => !templates[k]) : [], canGenerate = verified && routes.length > 0;
 useEffect(() => setEvidence(verified && evidenceKey ? loadPacketAssets(evidenceKey) : emptyEvidence()), [verified, evidenceKey]);
 function clearOutputs() { setDocs([]); setWarnings([]); setWorkingZip(null); setPackets([]); setFinalZip(null); setDocDate(''); }
 function captureDraft(label: string) { if (source.trim()) setRecoveryDraft({ text: source, normalized, label, capturedAt: new Date().toISOString() }); }
 function saveCase(status: ClientCaseStatus, data: Partial<ClientCaseRecord> = {}) { const id = data.id || caseId, name = data.clientName || parsed.name; if (!id || !name) return null; const old = cases.find((x) => x.id === id); const r: ClientCaseRecord = { id, clientName: name, round, routeCount: routes.length, bureaus: Array.from(new Set(routes.map((x) => x.bureau))), evidenceCount: data.evidenceCount ?? old?.evidenceCount ?? evidence.supporting.length, editableCount: data.editableCount ?? old?.editableCount ?? docs.length, pdfCount: data.pdfCount ?? old?.pdfCount ?? packets.length, status, updatedAt: new Date().toISOString() }; setCases(upsertClientCase(r)); return r; }
 function begin() { setRound(preferences.defaultRound); setSource(''); setOriginalSource(''); setRecoveryDraft(null); setNormalized(false); setCaseId(''); setEvidence(emptyEvidence()); clearOutputs(); setPanel('Source Data'); }
 function importSource(value: string, action: string) { if (!value.trim()) return; if (source.trim()) captureDraft(`Working draft preserved before ${action.toLowerCase()} replacement`); const text = createNormalizedSourceCopy(value).text, p = parseSource(text), id = crypto.randomUUID(); setOriginalSource(value); setSource(text); setNormalized(true); setCaseId(id); setEvidence(emptyEvidence()); clearOutputs(); if (p.name) { const r = detectRoutes(p); const rec: ClientCaseRecord = { id, clientName: p.name, round, routeCount: r.length, bureaus: Array.from(new Set(r.map((x) => x.bureau))), evidenceCount: 0, editableCount: 0, pdfCount: 0, status: 'SOURCE_LOCKED', updatedAt: new Date().toISOString() }; setCases(upsertClientCase(rec)); } setStatus(`${action} source imported and protected as the original baseline.`); }
 function standardizeDraft(value: string) { if (!value.trim()) return; const text = createNormalizedSourceCopy(value).text, p = parseSource(text), id = caseId || crypto.randomUUID(); setSource(text); setNormalized(true); if (!caseId) setCaseId(id); clearOutputs(); if (p.name) { const r = detectRoutes(p); const rec: ClientCaseRecord = { id, clientName: p.name, round, routeCount: r.length, bureaus: Array.from(new Set(r.map((x) => x.bureau))), evidenceCount: evidence.supporting.length, editableCount: 0, pdfCount: 0, status: evidence.supporting.length ? 'EVIDENCE_READY' : 'SOURCE_LOCKED', updatedAt: new Date().toISOString() }; setCases(upsertClientCase(rec)); } setStatus('Working draft standardized. The imported original remains protected and evidence has been retained.'); }
 function startManualDraft(value: string) { if (source.trim()) captureDraft('Working draft preserved before blank manual format'); setOriginalSource(''); setSource(value); setNormalized(false); setCaseId(crypto.randomUUID()); setEvidence(emptyEvidence()); clearOutputs(); setStatus('Manual draft opened. Importing a TXT later will require confirmation before replacement.'); }
 function restoreOriginal() { if (!originalSource.trim()) return; if (source.trim() && source !== originalSource) captureDraft('Working draft saved before restoring imported original'); setSource(originalSource); setNormalized(false); clearOutputs(); setStatus('Imported original restored. Your previous working draft is available through Recover saved draft. Supporting evidence was retained.'); }
 function recoverDraft() { if (!recoveryDraft) return; const active: SourceDraftSnapshot = { text: source, normalized, label: 'Version saved before draft recovery', capturedAt: new Date().toISOString() }; const restored = recoveryDraft; setSource(restored.text); setNormalized(restored.normalized); setRecoveryDraft(active); clearOutputs(); setStatus(`${restored.label} recovered. Supporting evidence was retained.`); }
 function setLine(key: string, value: string) { const pattern = new RegExp(`^${key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}:.*$`, 'im'), line = `${key}: ${value}`, anchor = /\n\s*\n(?=(FTC AFFECTED ACCOUNTS|DISPUTE ACCOUNTS|HARD INQUIRIES|LATE PAYMENTS)\b)/i; setSource(pattern.test(source) ? source.replace(pattern, line) : anchor.test(source) ? source.replace(anchor, `\n${line}\n\n`) : `${source.trim()}\n${line}`); setNormalized(true); clearOutputs(); }
 function setAccounts(items: FtcAffectedAccount[]) { const match = /FTC AFFECTED ACCOUNTS[\s\S]*?(?=\n\s*\n(?:DISPUTE ACCOUNTS|HARD INQUIRIES|LATE PAYMENTS|PRESERVED SOURCE DATA)\b|$)/i, block = ftcSection(items, parsed.ftcReportDate); setSource(match.test(source) ? source.replace(match, block) : `${source.trim()}\n\n${block}`); setNormalized(true); clearOutputs(); }
 function seedAccounts() { const found: FtcAffectedAccount[] = [], seen = new Set<string>(); bureaus.flatMap((b) => parsed.dispute[b]).forEach((x) => { if (found.length >= MAX_FTC_ACCOUNTS || !x.ftcDerived?.dateDiscovered) return; const parts = x.displayText.split('\n'), accountName = (parts.find((p) => /^Account Name:/i.test(p)) || '').replace(/^Account Name:\s*/i, ''), accountNumber = (parts.find((p) => /^Account Number:/i.test(p)) || '').replace(/^Account Number:\s*/i, ''), k = `${accountName}|${accountNumber}|${x.ftcDerived.dateDiscovered}`.toUpperCase(); if (!seen.has(k)) { seen.add(k); found.push({ accountName, accountNumber, fraudBegan: ftcFraudMonthYearFromReportDate(parsed.ftcReportDate), dateDiscovered: x.ftcDerived.dateDiscovered, fraudulentAmount: x.ftcDerived.fraudulentAmount }); } }); setAccounts(found.length ? found : [{ accountName: '', accountNumber: '', fraudBegan: ftcFraudMonthYearFromReportDate(parsed.ftcReportDate), dateDiscovered: '', fraudulentAmount: '' }]); }
 async function uploadRef(slot: LetterReference, file: File) { if (!isDocx(file.name)) return setStatus('Letter references accept DOCX files only.'); const contract = await saveReferenceFile(slot, file); setReferences((xs) => xs.map((x) => x.id === slot.id ? { ...x, file: file.name, size: file.size, contract } : x)); clearOutputs(); }
 async function removeRef(slot: LetterReference) { await removeReferenceFile(slot.id); setReferences((xs) => xs.map((x) => x.id === slot.id ? { ...x, file: '', size: undefined, contract: undefined } : x)); clearOutputs(); }
 async function letter(route: LetterRoute, file: File, date: string) { const recipient = bureauInfo[route.bureau], identity = { consumerName: parsed.name, addressLines: parsed.address, dob: parsed.dob, ssn: parsed.ssn, letterDate: date, bureauName: recipient.name, bureauAddressLines: recipient.address.split('\n') }; return route.type === 'DISPUTE' ? renderReferenceDisputeDocx(file, { ...identity, disputeItems: route.items.filter((x) => x.type === 'DISPUTE_ACCOUNT').map((x) => x.displayText), hardInquiryItems: route.items.filter((x) => x.type === 'HARD_INQUIRY').map((x) => x.displayText) }) : renderLatePaymentReference(file, { ...identity, latePaymentItems: route.items.map((x) => x.displayText) }); }
 async function supplement(kind: 'AFFIDAVIT' | 'FTC', bureau: Bureau, date: string) { const file = await readTemplateExhibit(round, kind); if (!file) return null; const r = bureauInfo[bureau], appendixSource = kind === 'AFFIDAVIT' ? affidavitSource : { ...parsed, ftcAccounts: normalizedFtcAccounts(parsed.ftcAccounts, parsed.ftcReportDate) }; const output = await renderMappedAppendix(file, { kind, bureau, documentDate: date, recipientName: r.name, recipientAddressLines: r.address.split('\n'), source: appendixSource }); return kind === 'AFFIDAVIT' && affidavitJurisdiction.reviewRequired ? highlightTextInDocx(output, 'N/A') : output; }
 async function makeZip(items: ReviewOutput[], notes: string[], date: string) { const zip = new JSZip(); items.forEach((x) => zip.file(x.path, x.blob)); await addOrderedPacketFolders(zip, items, round, evidenceKey, parsed.name, routes.map((r) => ({ type: r.type, bureau: r.bureau }))); zip.file('Generation Manifest.txt', ['WORKING DOCUMENTS', `Client: ${parsed.name}`, `Round: ${round}`, `Date: ${date}`, 'Affidavit and FTC are shared client documents reused inside applicable dispute packets.', ...items.map((x) => `- ${x.path}`), ...notes.map((x) => `- ${x}`)].join('\n')); return zip.generateAsync({ type: 'blob' }); }
 async function generate() { if (!canGenerate || !evidence.supporting.length || !affidavitReady || !ftcReady || !customReady || (preferences.strictValidation && missingLetters.length)) { setStatus(!ftcReady ? 'Complete FTC report-number and affected-item source data.' : 'Complete required generation checks first.'); return; } setBusy(true); const date = dateNow(), out: ReviewOutput[] = [], notes = missingNodes.map((k) => `${exhibitTitles[k]} is not configured; its position remains blank.`); for (const route of routes) { const ref = refs.find((x) => x.type === route.type), file = ref?.file ? await readReferenceFile(ref.id) : null; if (!file) { notes.push(`${labels[route.type]} / ${route.bureau}: DOCX reference is missing.`); continue; } try { out.push({ id: `${route.type}-${route.bureau}-LETTER`, path: `Editable Documents/${clean(parsed.name)} ${route.bureau} ${labels[route.type]}.docx`, type: route.type, role: 'LETTER', sequence: 1, bureau: route.bureau, count: route.items.length, detail: route.reason, blob: await letter(route, file, date), packetSteps: order(route.type) }); } catch (e) { notes.push(`${labels[route.type]} / ${route.bureau}: ${e instanceof Error ? e.message : 'Generation failed.'}`); } } const context = routes.find((r) => r.type === 'DISPUTE'); if (context && affidavitRequired) { try { const file = await supplement('AFFIDAVIT', context.bureau, date); if (file) out.push({ id: 'CLIENT-AFFIDAVIT', path: `Editable Documents/${clean(parsed.name)} 04 ${exhibitTitles.AFFIDAVIT}.docx`, type: 'DISPUTE', role: 'AFFIDAVIT', sequence: 4, bureau: 'CLIENT', count: 1, detail: 'Shared client affidavit', blob: file, packetSteps: order('DISPUTE') }); } catch (e) { notes.push(`Affidavit: ${e instanceof Error ? e.message : 'Generation failed.'}`); } } if (context && ftcRequired) { try { const file = await supplement('FTC', context.bureau, date); if (file) out.push({ id: 'CLIENT-FTC', path: `Editable Documents/${clean(parsed.name)} 06 ${exhibitTitles.FTC}.docx`, type: 'DISPUTE', role: 'FTC', sequence: 6, bureau: 'CLIENT', count: Math.min(parsed.ftcAccounts.length, MAX_FTC_ACCOUNTS), detail: 'Shared client FTC report', blob: file, packetSteps: order('DISPUTE') }); } catch (e) { notes.push(`FTC Report: ${e instanceof Error ? e.message : 'Generation failed.'}`); } } const z = await makeZip(out, notes, date); setDocs(out); setWarnings(notes); setWorkingZip({ name: `${base(parsed.name)}_${base(round)}_WORKING_DOCUMENTS.zip`, blob: z }); setDocDate(date); setPackets([]); setFinalZip(null); setBusy(false); saveCase('REVIEW_READY', { editableCount: out.length, evidenceCount: evidence.supporting.length, pdfCount: 0 }); setPanel('Outputs'); }
 async function saveEdited(output: ReviewOutput, file: File) { const out = docs.map((x) => x.path === output.path ? { ...x, blob: file } : x), z = await makeZip(out, warnings, docDate || dateNow()); setDocs(out); setWorkingZip({ name: workingZip?.name || 'WORKING_DOCUMENTS.zip', blob: z }); setPackets([]); setFinalZip(null); }
 async function assemble(type: LetterType, bureau: string, items: ReviewOutput[], finalDelivery = false) { const supporting = evidenceKey ? await createSupportingDocumentsPdf(evidenceKey).catch(() => null) : null, letterDoc = items.find((x) => x.type === type && x.bureau === bureau && x.role === 'LETTER'); if (!supporting) throw new Error('Required Supporting Documents page could not be prepared.'); const parts: PdfPacketPart[] = [letterDoc ? { label: labels[type], kind: 'DOCX', blob: letterDoc.blob } : { label: labels[type], kind: 'BLANK' }, { label: 'Supporting Documents', kind: 'PDF', blob: supporting }]; if (type === 'DISPUTE') { const fcra = await readTemplateExhibit(round, 'FCRA'), attachment = await readTemplateExhibit(round, 'ATTACHMENT'), affidavit = items.find((x) => x.role === 'AFFIDAVIT' && (x.bureau === bureau || x.bureau === 'CLIENT')), ftc = items.find((x) => x.role === 'FTC' && (x.bureau === bureau || x.bureau === 'CLIENT')); parts.push(fcra ? { label: 'FCRA', kind: 'PDF', blob: fcra } : { label: 'FCRA', kind: 'BLANK' }, affidavit ? { label: 'Affidavit', kind: 'DOCX', blob: affidavit.blob } : { label: 'Affidavit', kind: 'BLANK' }, attachment ? { label: 'Attachment', kind: 'PDF', blob: attachment } : { label: 'Attachment', kind: 'BLANK' }, ftc ? { label: 'FTC', kind: 'DOCX', blob: ftc.blob } : { label: 'FTC', kind: 'BLANK' }); } return assembleFinalPdf(parts, { requireAllParts: finalDelivery }); }
 async function preview(output: ReviewOutput, pending: Blob): Promise<FinalPdfPacket> { const items = docs.map((x) => x.path === output.path ? { ...x, blob: pending } : x); return { path: `Preview/${clean(parsed.name)} ${output.bureau} PACKET.pdf`, type: output.type, bureau: output.bureau, sequence: order(output.type), blob: await assemble(output.type, output.bureau, items) }; }
 async function finalize() { if (!evidence.supporting.length || !affidavitReady || !ftcReady || !customReady) { setStatus('Complete required evidence and document information before final PDF creation.'); return; } setFinalizing(true); try { const final: FinalPdfPacket[] = []; for (const route of routes) final.push({ path: `Final PDF Packets/${route.type === 'DISPUTE' ? 'DISPUTE PACKETS' : 'LATE PAYMENT PACKETS'}/${clean(parsed.name)} ${route.bureau} PACKET.pdf`, type: route.type, bureau: route.bureau, sequence: order(route.type), blob: await assemble(route.type, route.bureau, docs, true) }); const zip = new JSZip(); final.forEach((x) => zip.file(x.path, x.blob)); setPackets(final); setFinalZip({ name: `${base(parsed.name)}_${base(round)}_FINAL_PDF_PACKETS.zip`, blob: await zip.generateAsync({ type: 'blob' }) }); const record = saveCase('PDF_READY', { pdfCount: final.length }); if (record) setFilings(addFinalFilings(record, final.map((x) => ({ bureau: x.bureau, type: x.type, path: x.path })))); if (preferences.openTrackerAfterFinalization) setPanel('Filing Tracker'); } catch (e) { setStatus(e instanceof Error ? e.message : 'Final PDF creation failed.'); } finally { setFinalizing(false); } }
 function dashboard() { return <DashboardOperationsWorkspace cases={cases} filings={filings} activeCaseId={caseId} onNewCase={begin} onOpenTemplates={() => setPanel('Templates')} onOpenOutputs={() => setPanel(workingZip ? 'Outputs' : 'Dashboard')} onOpenTracker={() => setPanel('Filing Tracker')} onContinueCase={(x) => setPanel(x.id === caseId && x.status !== 'PDF_READY' ? (x.status === 'REVIEW_READY' ? 'Outputs' : 'Source Data') : 'Filing Tracker')} />; }
 function sourceView() { return <GuidedSourceDataFlow source={source} originalSource={originalSource} recoveryDraft={recoveryDraft} normalized={normalized} verified={verified} parsed={affidavitRequired ? affidavitSource : parsed} routes={routes} sourceWarnings={sourceWarnings} evidenceKey={evidenceKey} evidence={evidence} canGenerate={canGenerate} missingLetters={missingLetters.map((x) => labels[x])} missingInsertCount={missingNodes.length} affidavitRequired={affidavitRequired} ftcRequired={ftcRequired} customFields={customFields} strict={preferences.strictValidation} busy={busy} onImportSource={importSource} onStandardizeDraft={standardizeDraft} onStartManualDraft={startManualDraft} onEditSource={(v) => { setSource(v); setNormalized(false); clearOutputs(); }} onSourceFieldChange={setLine} onFtcAccountChange={(i, k, v) => setAccounts(parsed.ftcAccounts.map((x, n) => n === i ? { ...x, [k]: v } : x))} onFtcAccountAdd={() => parsed.ftcAccounts.length < MAX_FTC_ACCOUNTS && setAccounts([...parsed.ftcAccounts, { accountName: '', accountNumber: '', fraudBegan: ftcFraudMonthYearFromReportDate(parsed.ftcReportDate), dateDiscovered: '', fraudulentAmount: '' }])} onFtcAccountRemove={(i) => setAccounts(parsed.ftcAccounts.filter((_, n) => n !== i))} onFtcAccountSeed={seedAccounts} onRestoreOriginal={restoreOriginal} onRecoverDraft={recoverDraft} onEvidenceChanged={(v) => { setEvidence(v); clearOutputs(); saveCase(v.supporting.length ? 'EVIDENCE_READY' : 'SOURCE_LOCKED', { evidenceCount: v.supporting.length, editableCount: 0, pdfCount: 0 }); }} onMessage={setStatus} onGenerate={generate} />; }
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span /><div><strong>LetterGenerator</strong><small>Packet workflow</small></div></div><nav>{panels.map((x) => <button key={x} className={panel === x ? 'active' : ''} disabled={x === 'Outputs' && !workingZip} onClick={() => setPanel(x)}><strong>{x}</strong></button>)}</nav></aside><section className="main-area"><header className="header"><div><p className="eyebrow">{panel === 'Dashboard' ? 'Client operations' : `${round} workflow`}</p><h1>{panel}</h1></div></header>{panel === 'Dashboard' && dashboard()}{panel === 'Templates' && <TemplateProgressiveWorkspace round={round} slots={refs} supportingReady={evidence.supporting.length > 0} onSelectRound={(x) => { setRound(x); clearOutputs(); }} onUploadLetter={uploadRef} onRemoveLetter={removeRef} onExhibitsChange={(x) => { setTemplates(x); clearOutputs(); }} onMessage={setStatus} />}{panel === 'Source Data' && sourceView()}{panel === 'Outputs' && <OutputReviewWorkspace round={round} outputs={docs} zipName={workingZip?.name} warnings={warnings} finalPackets={packets} finalizing={finalizing} finalZipName={finalZip?.name} evidenceKey={evidenceKey} evidence={evidence} onEvidenceChanged={(x) => setEvidence(x)} onMessage={setStatus} onZip={() => workingZip && download(workingZip.name, workingZip.blob)} onFinalZip={() => finalZip && download(finalZip.name, finalZip.blob)} onFinalize={finalize} onPreviewPacket={preview} onPdfDownload={(x) => download(x.path.split('/').pop() || 'packet.pdf', x.blob)} onReplace={saveEdited} />}{panel === 'Filing Tracker' && <FilingTrackerWorkspace records={filings} outputsAvailable={Boolean(workingZip)} onReturnToOutputs={() => setPanel('Outputs')} onStartCase={begin} onMarkSent={(id) => setFilings(markFilingSent(id))} />}{panel === 'Settings' && <WorkspaceSettingsPanel preferences={preferences} caseCount={cases.length} filingCount={filings.length} onChange={(x) => setPreferences(saveWorkspacePreferences(x))} onExportRecords={() => download('LETTERGENERATOR_OPERATIONAL_RECORDS.json', new Blob([JSON.stringify(exportOperationsRecords(), null, 2)], { type: 'application/json' }))} onClearRecords={() => { const v = clearOperationsRecords(); setCases(v.cases); setFilings(v.filings); }} />}</section></main>;
}
