import PizZip from 'pizzip';
import { DOCX_MIME, renderDocxTemplate, type PlaceholderValues } from './docx-renderer';
import { bureaus, ftcFraudMonthYearFromReportDate, MAX_FTC_ACCOUNTS, type Bureau, type FtcAffectedAccount, type ParsedSource, type SourceItem } from './letter-engine';

export type MappedAppendixKind = 'AFFIDAVIT' | 'FTC';
export type MappedAppendixContext = { kind: MappedAppendixKind; bureau: Bureau; documentDate: string; recipientName: string; recipientAddressLines: string[]; source: ParsedSource };
const WORD_NS = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const XML_NS = 'http://www.w3.org/XML/1998/namespace';
type RenderRow = { account_name: string; account_number: string; account_line: string; display_text: string };
type HighlightGroup = Element[];
function rows(items: SourceItem[]) { return items.map((item) => { const lines = item.displayText.split('\n').map((line) => line.trim()).filter(Boolean); const itemName = (lines.find((line) => /^Account Name:/i.test(line)) || '').replace(/^Account Name:\s*/i, ''); const itemNumber = (lines.find((line) => /^Account Number:/i.test(line)) || '').replace(/^Account Number:\s*/i, ''); return { account_name: itemName, account_number: itemNumber, account_line: [itemName, itemNumber].filter(Boolean).join(' — '), display_text: item.displayText }; }); }
function phoneForFtc(value: string) { const clean = value.trim(); if (!clean) return 'N/A'; const digits = clean.replace(/\D/g, ''); return digits.length === 10 ? `${digits.slice(0, 3)}-${digits.slice(3, 6)}-${digits.slice(6)}` : clean; }
function consolidatedDisputeAccounts(source: ParsedSource) {
  const grouped = new Map<string, Map<string, { row: RenderRow; bureaus: Set<Bureau> }>>();
  bureaus.forEach((bureau) => rows(source.dispute[bureau]).forEach((row) => { const name = row.account_name.toUpperCase(); const number = row.account_number.toUpperCase(); if (!grouped.has(name)) grouped.set(name, new Map()); const versions = grouped.get(name)!; if (!versions.has(number)) versions.set(number, { row, bureaus: new Set() }); versions.get(number)!.bureaus.add(bureau); }));
  const result: RenderRow[] = []; grouped.forEach((versions) => { const candidates = Array.from(versions.values()); const repeated = candidates.filter((candidate) => candidate.bureaus.size > 1); (repeated.length ? repeated : candidates).forEach((candidate) => result.push(candidate.row)); }); return result;
}
function affidavitRows(source: ParsedSource) { const accountRows = consolidatedDisputeAccounts(source); const seen = new Set(accountRows.map((item) => item.account_line.toUpperCase())); const inquiryRows: RenderRow[] = []; bureaus.forEach((bureau) => source.inquiry[bureau].forEach((item) => { const line = item.displayText.replace(/\s+-\s+/g, ' — '); const key = line.toUpperCase(); if (!seen.has(key)) { seen.add(key); inquiryRows.push({ account_name: '', account_number: '', account_line: line, display_text: item.displayText }); } })); return [...accountRows, ...inquiryRows]; }
function ftcRows(items: FtcAffectedAccount[], reportDate: string) { const fraudBegan = ftcFraudMonthYearFromReportDate(reportDate); return items.slice(0, MAX_FTC_ACCOUNTS).map((item) => ({ account_name: item.accountName, account_number: item.accountNumber, fraud_began: fraudBegan, date_discovered: item.dateDiscovered, fraudulent_amount: item.fraudulentAmount, fraud_amount: item.fraudulentAmount })); }
function mappedValues(context: MappedAppendixContext): PlaceholderValues { const bureauAccounts = rows(context.source.dispute[context.bureau]); const affidavitAccounts = affidavitRows(context.source); const accounts = context.kind === 'AFFIDAVIT' ? affidavitAccounts : bureauAccounts; const inquiries = context.source.inquiry[context.bureau].map((item) => ({ inquiry_line: item.displayText, display_text: item.displayText })); const phone = context.kind === 'FTC' ? phoneForFtc(context.source.phone) : context.source.phone; const reportDate = context.source.ftcReportDate || context.documentDate; return { consumer_name: context.source.name, client_name: context.source.name, name: context.source.name, consumer_first_name: context.source.firstName, consumer_middle_name: context.kind === 'FTC' ? '' : context.source.middleName, consumer_last_name: context.source.lastName, address: context.source.address.join('\n'), address_inline: context.source.address.join(' '), address_line_1: context.source.address[0] || '', address_line_2: context.source.address.slice(1).join(' '), country: context.source.country || 'USA', dob: context.source.dob, ssn: context.source.ssn, ssn_masked: context.source.ssn, phone, email: context.kind === 'FTC' ? '' : context.source.email, date: context.documentDate, letter_date: context.documentDate, document_date: context.documentDate, affidavit_state: context.source.affidavitState, affidavit_county: context.source.affidavitCounty, ftc_report_number: context.source.ftcReportNumber, ftc_report_date: reportDate, bureau_name: context.recipientName, bureau_address: context.recipientAddressLines.join('\n'), bureau_address_line_1: context.recipientAddressLines[0] || '', bureau_address_line_2: context.recipientAddressLines.slice(1).join(' '), accounts, dispute_accounts: accounts, ftc_accounts: ftcRows(context.source.ftcAccounts, reportDate), hard_inquiries: inquiries, account_lines: accounts.map((item) => item.account_line).join('\n'), hard_inquiry_lines: inquiries.map((item) => item.inquiry_line).join('\n'), ...context.source.templateFields }; }
function paragraphs(root: Element) { return Array.from(root.getElementsByTagNameNS(WORD_NS, 'p')); }
function content(root: Element) { return Array.from(root.getElementsByTagNameNS(WORD_NS, 't')).map((node) => node.textContent || '').join('').trim(); }
function runs(root: Element) { return Array.from(root.getElementsByTagNameNS(WORD_NS, 'r')); }
function yellowHighlight(run: Element) { return Array.from(run.getElementsByTagNameNS(WORD_NS, 'highlight')).some((highlight) => { const value = (highlight.getAttributeNS(WORD_NS, 'val') || highlight.getAttribute('w:val') || '').toLowerCase(); return !value || value === 'yellow'; }); }
function highlightGroups(root: Element): HighlightGroup[] { const groups: HighlightGroup[] = []; let current: HighlightGroup | null = null; runs(root).forEach((run) => { if (yellowHighlight(run)) { if (!current) { current = []; groups.push(current); } current.push(run); } else current = null; }); return groups; }
function groupContent(group: HighlightGroup) { return group.map((run) => content(run)).join('').trim(); }
function removeYellow(run: Element) { Array.from(run.getElementsByTagNameNS(WORD_NS, 'highlight')).forEach((highlight) => { const value = (highlight.getAttributeNS(WORD_NS, 'val') || highlight.getAttribute('w:val') || '').toLowerCase(); if ((!value || value === 'yellow') && highlight.parentNode) highlight.parentNode.removeChild(highlight); }); }
function clearRunContent(run: Element) { Array.from(run.children).forEach((node) => { if (!(node.namespaceURI === WORD_NS && node.localName === 'rPr')) run.removeChild(node); }); }
function writeRunValue(run: Element, value: string) { const doc = run.ownerDocument; clearRunContent(run); removeYellow(run); value.replace(/\r/g, '').split('\n').forEach((line, index) => { if (index) run.appendChild(doc.createElementNS(WORD_NS, 'w:br')); const text = doc.createElementNS(WORD_NS, 'w:t'); if (/^\s|\s$/.test(line)) text.setAttributeNS(XML_NS, 'xml:space', 'preserve'); text.textContent = line; run.appendChild(text); }); }
function fillGroup(group: HighlightGroup, value: string) { if (!group.length) return false; writeRunValue(group[0], value); group.slice(1).forEach((run) => { clearRunContent(run); removeYellow(run); }); return true; }
function fillValue(group: HighlightGroup, value: string) { const prefix = groupContent(group).match(/^([^:\n]{1,45}:\s*)/); return fillGroup(group, prefix ? `${prefix[1]}${value}` : value); }
function fillSingleSlot(paragraph: Element | undefined, value: string, label: string) { const group = paragraph ? highlightGroups(paragraph)[0] : undefined; if (!group || !fillValue(group, value)) throw new Error(`The uploaded template is missing a highlighted ${label} insertion field.`); }
function fillDynamicSentence(paragraph: Element | undefined, values: string[], combined: string, label: string) { if (!paragraph) throw new Error(`The uploaded template is missing the ${label} paragraph.`); const groups = highlightGroups(paragraph); if (groups.length >= values.length) { values.forEach((value, index) => fillValue(groups[index], value)); return; } if (groups.length === 1) { fillValue(groups[0], combined); return; } throw new Error(`The uploaded template is missing highlighted ${label} insertion fields.`); }
function contextText(node: Element) { let current: Element | null = node; let fallback = ''; while (current) { const value = content(current); if (value.length > fallback.length) fallback = value; if (current.namespaceURI === WORD_NS && (current.localName === 'tc' || current.localName === 'tr')) return value; current = current.parentElement; } return fallback; }
function parentTable(node: Element, body: Element) { let current: Node | null = node; while (current && current !== body) { if ((current as Element).namespaceURI === WORD_NS && (current as Element).localName === 'tbl') return current as Element; current = current.parentNode; } return null; }
async function openTemplate(template: File, label: string) { const zip = new PizZip(await template.arrayBuffer()), file = zip.file('word/document.xml'); if (!file) throw new Error(`${label} DOCX document XML is unavailable.`); const xml = new DOMParser().parseFromString(file.asText(), 'application/xml'), body = xml.getElementsByTagNameNS(WORD_NS, 'body')[0]; if (!body) throw new Error(`${label} DOCX body is unavailable.`); return { zip, xml, body }; }
function finalize(zip: PizZip, xml: XMLDocument) { zip.file('word/document.xml', new XMLSerializer().serializeToString(xml)); return zip.generate({ type: 'blob', mimeType: DOCX_MIME, compression: 'DEFLATE' }); }
function fillByContext(groups: HighlightGroup[], mappings: Array<{ pattern: RegExp; value: string }>) { const used = new Set<number>(); mappings.forEach((mapping) => { const index = groups.findIndex((group, candidate) => !used.has(candidate) && mapping.pattern.test(contextText(group[0]))); if (index >= 0) { fillValue(groups[index], mapping.value); used.add(index); } }); return used; }
async function renderHighlightedAffidavit(template: File, context: MappedAppendixContext) {
  const { zip, xml, body } = await openTemplate(template, 'Affidavit'); const all = paragraphs(body); const source = context.source; const accounts = affidavitRows(source), street = source.address[0] || 'N/A'; const find = (pattern: RegExp) => all.find((paragraph) => pattern.test(content(paragraph)));
  const state = find(/^State of\s*:/i), county = find(/^County of\s*:/i), opening = find(/^I,\s/i), personal = find(/^(?:1\.\s*)?Personal Information\s*:/i), date = find(/^Date\s*:/i);
  fillSingleSlot(state, source.affidavitState || 'N/A', 'State of'); fillSingleSlot(county, source.affidavitCounty || 'N/A', 'County of'); fillDynamicSentence(opening, [source.name, street], `${source.name} residing at ${street}`, 'affidavit opening'); fillDynamicSentence(personal, [street, source.ssn], `${street}. My Social Security number is ${source.ssn}`, 'personal information'); fillSingleSlot(date, context.documentDate, 'date');
  const closeIndex = all.findIndex((paragraph) => /^Sincerely,?$/i.test(content(paragraph))); const signature = closeIndex >= 0 ? all.slice(closeIndex + 1).find((paragraph) => highlightGroups(paragraph).length > 0) : undefined; fillSingleSlot(signature, source.name, 'signature');
  const headingIndex = all.findIndex((paragraph) => /^Account Information\s*:/i.test(content(paragraph))); const statementIndex = all.findIndex((paragraph) => /^I declare that this account/i.test(content(paragraph)));
  if (headingIndex >= 0 && statementIndex > headingIndex) { const region = all.slice(headingIndex + 1, statementIndex); const sample = region.find((paragraph) => highlightGroups(paragraph).length > 0); if (!sample || !sample.parentNode) throw new Error('The uploaded affidavit template is missing a highlighted repeating account row.'); accounts.forEach((account) => { const row = sample.cloneNode(true) as Element; const groups = highlightGroups(row); if (groups.length >= 2 && account.account_name) { fillValue(groups[0], account.account_name); fillValue(groups[1], account.account_number); } else fillValue(groups[0], account.account_line); sample.parentNode!.insertBefore(row, sample); }); region.filter((paragraph) => highlightGroups(paragraph).length > 0).forEach((paragraph) => paragraph.parentNode?.removeChild(paragraph)); }
  return finalize(zip, xml);
}
async function renderHighlightedFtc(template: File, context: MappedAppendixContext) {
  const { zip, xml, body } = await openTemplate(template, 'FTC Report'); const all = paragraphs(body); const source = context.source; const reportDate = source.ftcReportDate || context.documentDate; const fraudBegan = ftcFraudMonthYearFromReportDate(reportDate), phone = phoneForFtc(source.phone);
  if (!source.ftcReportNumber.trim() || !reportDate.trim()) throw new Error('FTC report number and report date are required.'); if (!source.ftcAccounts.length) throw new Error('At least one FTC affected item is required.');
  const report = all.find((paragraph) => /^FTC Report Number\s*:/i.test(content(paragraph))); fillSingleSlot(report, source.ftcReportNumber, 'FTC report number'); const narrativeIndex = all.findIndex((paragraph) => /IMMEDIATE ENFORCEMENT|FCRA SECTION/i.test(content(paragraph))), statementIndex = all.findIndex((paragraph) => /knowingly making any false statements/i.test(content(paragraph))); if (narrativeIndex < 0 || statementIndex < 0) throw new Error('FTC highlighted template structure is incomplete.');
  const reportIndex = report ? all.indexOf(report) : -1; const identityGroups = all.slice(reportIndex + 1, narrativeIndex).flatMap((paragraph) => highlightGroups(paragraph)); const identityMap = [{ pattern: /first\s+name/i, value: source.firstName }, { pattern: /middle\s+name/i, value: '' }, { pattern: /last\s+name/i, value: source.lastName }, { pattern: /address|street/i, value: source.address.join('\n') }, { pattern: /country/i, value: source.country || 'USA' }, { pattern: /phone|telephone|mobile/i, value: phone }, { pattern: /e-?mail/i, value: '' }]; const used = fillByContext(identityGroups, identityMap); const unresolved = identityGroups.filter((_, index) => !used.has(index)); const fallbackValues = identityGroups.length >= 7 ? [source.firstName, '', source.lastName, source.address.join('\n'), source.country || 'USA', phone, ''] : [source.firstName, source.lastName, source.address.join('\n'), phone]; unresolved.forEach((group, index) => { if (fallbackValues[index] !== undefined) fillValue(group, fallbackValues[index]); });
  const candidateParagraphs = all.slice(narrativeIndex + 1, statementIndex).filter((paragraph) => highlightGroups(paragraph).length > 0); const detectedTables: Element[] = []; candidateParagraphs.forEach((paragraph) => { const table = parentTable(paragraph, body); if (table && !detectedTables.includes(table)) detectedTables.push(table); }); const templateTable = detectedTables[0]; if (!templateTable || !templateTable.parentNode) throw new Error('The uploaded FTC template is missing a highlighted reusable affected-item table.'); const parent = templateTable.parentNode;
  source.ftcAccounts.slice(0, MAX_FTC_ACCOUNTS).forEach((account, index) => { const table = detectedTables[index] || templateTable.cloneNode(true) as Element; const groups = highlightGroups(table); const values = [account.accountName, account.accountNumber, fraudBegan, account.dateDiscovered, account.fraudulentAmount ? `$ ${account.fraudulentAmount}` : '']; if (groups.length < values.length) throw new Error('The uploaded FTC affected-item table is missing required highlighted insertion fields.'); values.forEach((value, position) => fillValue(groups[position], value)); if (!detectedTables[index]) parent.insertBefore(table, templateTable); }); detectedTables.slice(Math.min(source.ftcAccounts.length, MAX_FTC_ACCOUNTS)).forEach((table) => table.parentNode?.removeChild(table));
  const tailGroups = all.slice(statementIndex + 1).flatMap((paragraph) => highlightGroups(paragraph)); const tailMap = [{ pattern: /signature|signed/i, value: source.name }, { pattern: /printed|print\s+name/i, value: source.name }, { pattern: /date/i, value: reportDate }]; const usedTail = fillByContext(tailGroups, tailMap); const tailFallback = [source.name, source.name, reportDate]; tailGroups.filter((_, index) => !usedTail.has(index)).slice(0, 3).forEach((group, index) => fillValue(group, tailFallback[index])); return finalize(zip, xml);
}
export async function renderMappedAppendix(template: File, context: MappedAppendixContext) { const text = await template.arrayBuffer().then((buffer) => new PizZip(buffer).file('word/document.xml')?.asText() || ''); if (text.includes('{{')) return renderDocxTemplate(template, mappedValues(context)); return context.kind === 'AFFIDAVIT' ? renderHighlightedAffidavit(template, context) : renderHighlightedFtc(template, context); }
